highlighter: rouge
paginate: 10
markdown: kramdown
host: 0.0.0.0

subscribe_rss: feed.xml
kramdown:
  input: GFM
  hard_wrap: false

home_url: "https://sungjungkim.github.io"
representing_image: "/images/yami-logo.png"

sass:
    sass_dir: css

trawler_mode: true
gems:
  - jekyll-paginate
  - jekyll-feed
feed:
  path: feed.xml
future: true
